"""koa jupyter -- Run Jupyter on a GPU compute node with SSH tunnel."""
from __future__ import annotations

import argparse
import random
import secrets
import signal
import socket
import subprocess
import time
from typing import Optional

from rich.console import Console

from ..config import Config
from ..ssh import SSHError, run_ssh
from ..slurm import SBATCH_JOB_ID_PATTERN, select_best_gpu

from . import add_common_arguments, emit_json, print_gpu_selection

console = Console()

POLL_INTERVAL = 3
POLL_TIMEOUT = 600  # 10 minutes


def _port_is_free(port: int) -> bool:
    """Return True if the local TCP port is available."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", port))
        return True
    except OSError:
        return False


def _ssh_tunnel_args(config: Config) -> list[str]:
    """Build base SSH args for the tunnel (no -tt, no SetEnv)."""
    args = ["ssh", "-o", "LogLevel=ERROR"]
    if config.identity_file:
        args.extend(["-i", str(config.identity_file)])
    if config.proxy_command:
        args.extend(["-o", f"ProxyCommand={config.proxy_command}"])
    return args


def _build_slurm_script(
    *,
    token: str,
    remote_port: int,
    lab: bool,
    conda_env: Optional[str],
) -> str:
    """Generate the SLURM batch script that starts Jupyter."""
    jupyter_cmd = "jupyter lab" if lab else "jupyter notebook"
    conda_block = ""
    if conda_env:
        conda_block = f"""
# Activate conda environment
eval "$(conda shell.bash hook)"
conda activate {conda_env}
"""

    return f"""#!/bin/bash
# Auto-generated by koa jupyter — do not edit
{conda_block}
{jupyter_cmd} \\
    --no-browser \\
    --ip=0.0.0.0 \\
    --port={remote_port} \\
    --ServerApp.token='{token}' \\
    --ServerApp.allow_origin='*'
"""


def _get_job_queue_position(
    config: Config,
    job_id: str,
    partition: Optional[str] = None,
    gpu_type: Optional[str] = None,
) -> Optional[int]:
    """Return the 1-indexed queue position for a pending job, or None.

    Filters by partition and GPU type so the position reflects how many
    people are ahead of you for the *same resource*, not the global queue.
    """
    try:
        cmd = ["squeue", "-t", "PD", "--sort=p,i", "-o", "%i|%b", "--noheader"]
        if partition:
            cmd.extend(["-p", partition])
        result = run_ssh(
            config,
            cmd,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            return None
        pos = 0
        for line in result.stdout.strip().splitlines():
            parts = line.split("|", 1)
            jid = parts[0].strip()
            gres = parts[1].strip() if len(parts) > 1 else ""
            # Skip jobs requesting a different GPU type
            if gpu_type and gpu_type.lower() not in gres.lower():
                continue
            pos += 1
            if jid == str(job_id):
                return pos
        return None
    except SSHError:
        return None


def _wait_for_running(
    config: Config,
    job_id: str,
    partition: Optional[str] = None,
    gpu_type: Optional[str] = None,
    timeout: int = POLL_TIMEOUT,
) -> str:
    """Poll squeue until the job is RUNNING. Returns the node name.

    Displays a Rich spinner with queue position during the wait.
    """
    elapsed = 0
    with console.status(
        f"[bold]Waiting for job {job_id} to start...[/bold]",
        spinner="dots",
    ) as status:
        while elapsed < timeout:
            result = run_ssh(
                config,
                ["squeue", "-j", job_id, "-h", "-o", "%T|%N"],
                capture_output=True,
                check=False,
            )
            output = (result.stdout or "").strip()
            if output:
                parts = output.split("|", 1)
                state = parts[0].strip()
                node = parts[1].strip() if len(parts) > 1 else ""
                if state == "RUNNING" and node:
                    return node
                if state in ("FAILED", "CANCELLED", "TIMEOUT", "NODE_FAIL"):
                    raise RuntimeError(f"Job {job_id} entered state {state}")
                if state == "PENDING":
                    pos = _get_job_queue_position(
                        config, job_id, partition, gpu_type
                    )
                    if pos is not None:
                        status.update(
                            f"[bold]Waiting for job {job_id}...[/bold] "
                            f"(queue position: #{pos})"
                        )
                    else:
                        status.update(
                            f"[bold]Waiting for job {job_id}...[/bold] "
                            f"(pending)"
                        )
            time.sleep(POLL_INTERVAL)
            elapsed += POLL_INTERVAL

    raise TimeoutError(
        f"Job {job_id} did not start within {timeout // 60} minutes"
    )


def _cleanup(
    config: Config,
    job_id: Optional[str],
    tunnel: Optional[subprocess.Popen],
    remote_script: Optional[str],
) -> None:
    """Cancel the SLURM job, kill the tunnel, and remove the remote script."""
    if tunnel and tunnel.poll() is None:
        tunnel.terminate()
        try:
            tunnel.wait(timeout=5)
        except subprocess.TimeoutExpired:
            tunnel.kill()

    if job_id:
        try:
            run_ssh(config, ["scancel", job_id], capture_output=True, check=False)
        except Exception:
            pass

    if remote_script:
        try:
            run_ssh(
                config,
                ["rm", "-f", remote_script],
                capture_output=True,
                check=False,
            )
        except Exception:
            pass


def register_parser(subparsers) -> argparse.ArgumentParser:
    parser = subparsers.add_parser(
        "jupyter",
        help="Run Jupyter on a GPU compute node with automatic SSH tunnel.",
    )
    parser.add_argument(
        "--time", "-t",
        default="04:00:00",
        help="Walltime limit (default: 04:00:00).",
    )
    parser.add_argument(
        "--gpus", "-g",
        type=int,
        default=1,
        help="Number of GPUs (default: 1).",
    )
    parser.add_argument(
        "--gpu-type",
        default=None,
        help="GPU type (default: auto-select best available).",
    )
    parser.add_argument(
        "--partition", "-p",
        default=None,
        help="Partition (default: from config).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8888,
        help="Local port for the tunnel (default: 8888).",
    )
    parser.add_argument(
        "--lab",
        action="store_true",
        default=True,
        help="Run jupyter lab (default).",
    )
    parser.add_argument(
        "--notebook",
        action="store_true",
        default=False,
        help="Run jupyter notebook instead of lab.",
    )
    parser.add_argument(
        "--conda-env",
        default=None,
        help="Conda environment to activate before starting Jupyter.",
    )
    parser.add_argument(
        "--mem",
        default="16G",
        help="Memory allocation (default: 16G).",
    )
    add_common_arguments(parser)
    return parser


def handle(args, config: Config) -> int:
    local_port: int = args.port
    use_lab: bool = not args.notebook
    partition = args.partition or config.default_partition or "kill-shared"
    mem: str = args.mem
    walltime: str = args.time
    gpus: int = args.gpus
    conda_env: str | None = args.conda_env

    # 1. Find a free local port
    if not _port_is_free(local_port):
        original_port = local_port
        for candidate in range(local_port + 1, local_port + 100):
            if _port_is_free(candidate):
                local_port = candidate
                break
        else:
            console.print(
                f"[red]No free port found near {original_port}.[/red]",
            )
            return 1
        console.print(
            f"Port {original_port} in use, using [bold]{local_port}[/bold] instead."
        )

    # 2. Generate token and random remote port
    token = secrets.token_hex(24)
    remote_port = random.randint(49152, 65535)

    # 3. GPU selection (skip for CPU-only mode)
    gpu_type = args.gpu_type
    if gpus > 0 and not gpu_type:
        console.print("Auto-selecting best available GPU...")
        gpu_type = select_best_gpu(config, partition, min_gpus=gpus)
        print_gpu_selection(config, gpu_type, gpus, partition, console=console)
    elif gpus == 0:
        console.print("[bold]CPU-only mode[/bold] (no GPU requested)")
        gpu_type = None

    # 4. Build SLURM script and write to remote
    script_content = _build_slurm_script(
        token=token,
        remote_port=remote_port,
        lab=use_lab,
        conda_env=conda_env,
    )
    script_hex = secrets.token_hex(8)
    remote_script = f"/tmp/koa-jupyter-{script_hex}.sh"

    try:
        run_ssh(
            config,
            f"cat > {remote_script} << 'KOAEOF'\n{script_content}KOAEOF",
            capture_output=True,
        )
    except SSHError as exc:
        console.print(f"[red]Failed to write remote script:[/red] {exc}")
        return 1

    # 5. Submit the job
    sbatch_cmd = [
        "sbatch",
        "--partition", partition,
        "--mem", mem,
        "--time", walltime,
        "--job-name", "koa-jupyter",
        "--output", f"/tmp/koa-jupyter-{script_hex}.log",
    ]
    if gpu_type and gpus > 0:
        sbatch_cmd.extend(["--gres", f"gpu:{gpu_type}:{gpus}"])
    sbatch_cmd.append(remote_script)

    job_id: str | None = None
    tunnel: subprocess.Popen | None = None

    try:
        console.print("Submitting Jupyter job...")
        result = run_ssh(config, sbatch_cmd, capture_output=True)
        output = (result.stdout or "").strip()
        match = SBATCH_JOB_ID_PATTERN.search(output)
        if not match:
            console.print(f"[red]Failed to parse job ID:[/red] {output}")
            _cleanup(config, None, None, remote_script)
            return 1
        job_id = match.group(1)
        console.print(f"Job [bold]{job_id}[/bold] submitted.")

        # 6. Poll until running
        node = _wait_for_running(
            config, job_id, partition=partition, gpu_type=gpu_type
        )
        console.print(f"Job [bold]{job_id}[/bold] running on [bold cyan]{node}[/bold cyan].")

        # 7. Open SSH tunnel
        tunnel_args = [
            *_ssh_tunnel_args(config),
            "-N",
            "-L", f"{local_port}:{node}:{remote_port}",
            config.login,
        ]
        tunnel = subprocess.Popen(
            tunnel_args,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )

        # Brief wait to catch immediate tunnel failures
        time.sleep(1)
        if tunnel.poll() is not None:
            stderr = (tunnel.stderr.read() or b"").decode(errors="replace")
            console.print(
                f"[red]SSH tunnel failed to start.[/red]\n{stderr}",
            )
            _cleanup(config, job_id, None, remote_script)
            return 1

        url = f"http://localhost:{local_port}/?token={token}"
        console.print(f"\nSSH tunnel: localhost:{local_port} -> {node}:{remote_port}")

        if args.output_format == "json":
            emit_json({
                "job_id": job_id,
                "node": node,
                "local_port": local_port,
                "remote_port": remote_port,
                "url": url,
                "token": token,
                "gpu_type": gpu_type,
                "gpus": gpus,
            })
        else:
            console.print(f"\n  [bold green]Jupyter URL:[/bold green] {url}")
            console.print(
                "\n  [dim]VS Code: Select Kernel -> Existing Jupyter Server -> paste URL[/dim]"
            )
            console.print("\nPress Ctrl+C to stop (cancels job and closes tunnel).")

        # 8. Wait for Ctrl+C
        # Block on the tunnel process — it runs until we kill it or it dies
        try:
            tunnel.wait()
        except KeyboardInterrupt:
            pass

    except KeyboardInterrupt:
        console.print("\n[bold]Interrupted.[/bold]")
    except TimeoutError as exc:
        console.print(f"\n[red]{exc}[/red]")
    except SSHError as exc:
        console.print(f"\n[red]SSH error:[/red] {exc}")
    except RuntimeError as exc:
        console.print(f"\n[red]{exc}[/red]")
    finally:
        console.print("Cleaning up...")
        _cleanup(config, job_id, tunnel, remote_script)
        console.print("Done.")

    return 0
